In [2]:
import arcpy
from arcpy import env
import os
from arcgis import GIS
from arcgis.features import GeoAccessor
import pandas as pd

arcpy.env.overwriteOutput = True
arcpy.env.parallelProcessingFactor = "90%"

# show all columns
pd.options.display.max_columns = None

# pd.DataFrame.spatial.from_featureclass(???)
# df.spatial.to_featureclass(location=???,sanitize_columns=False)

In [2]:
if not os.path.exists('Outputs'):
    os.makedirs('Outputs')
    
outputs = ['.\\Outputs', "scratch.gdb", 'remm_base_year.gdb']
# gdb = os.path.join(outputs[0], outputs[1])
# gdb2 = os.path.join(outputs[0], outputs[2])

# if not arcpy.Exists(gdb):
#     arcpy.CreateFileGDB_management(outputs[0], outputs[1])

# if not arcpy.Exists(gdb2):
#     arcpy.CreateFileGDB_management(outputs[0], outputs[2])

In [3]:
ag_parcels = r"E:\Tasks\Replace_HAFB_Parcels\Outputs\remm_base_year_20220513.gdb\ag_parcels_2019"
ag_parcels_df = pd.DataFrame.spatial.from_featureclass(ag_parcels)

In [4]:
agriculture = ag_parcels_df[['parcel_id_REMM']].copy()
agriculture.columns = ['parcel_id']
agriculture['Agriculture'] = 1

In [5]:
agriculture.to_csv(os.path.join(outputs[0], 'agriculture.csv'), index=False)

## Bonus: fix policy

In [25]:
zpp = pd.read_csv("E:\Projects\REMM-Input-Data-Prep-2019\Policy-Layer\Outputs\zoning_parcels_p.csv")
zpp

,parcel_id,max_dua,max_far,year,type1,type2,type3,type4,type5,type6,type7,type8,locnote,mponote
0,1,25.0,1.3,2019.0,0,1,0,1,1,0,0,0,WFRCCenters,WFRC
1,3,0.4,0.4,2019.0,0,0,1,0,0,0,0,0,WFRCCenters,WFRC
2,5,10.0,0.8,2019.0,1,1,0,1,1,0,0,0,WFRCCenters,WFRC
3,6,0.0,0.5,2019.0,0,0,0,1,1,0,0,0,WFRCCenters,WFRC
4,13,0.4,0.4,2019.0,0,0,1,0,0,0,0,0,WFRCCenters,WFRC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37244,762164,30.0,1.9,2019.0,0,1,0,1,1,0,0,0,WFRCCenters,WFRC
37245,762167,0.0,0.4,2019.0,0,0,1,0,0,0,0,0,WFRCCenters,WFRC
37246,762168,0.0,0.4,2019.0,0,0,1,0,0,0,0,0,WFRCCenters,WFRC
37247,762169,0.0,0.4,2019.0,0,0,1,0,0,0,0,0,WFRCCenters,WFRC
37248,762170,0.0,0.4,2019.0,0,0,1,0,0,0,0,0,WFRCCenters,WFRC

In [27]:
zpp2 = zpp.drop_duplicates(subset=['parcel_id','year'])
zpp2

,parcel_id,max_dua,max_far,year,type1,type2,type3,type4,type5,type6,type7,type8,locnote,mponote
0,1,25.0,1.3,2019.0,0,1,0,1,1,0,0,0,WFRCCenters,WFRC
1,3,0.4,0.4,2019.0,0,0,1,0,0,0,0,0,WFRCCenters,WFRC
2,5,10.0,0.8,2019.0,1,1,0,1,1,0,0,0,WFRCCenters,WFRC
3,6,0.0,0.5,2019.0,0,0,0,1,1,0,0,0,WFRCCenters,WFRC
4,13,0.4,0.4,2019.0,0,0,1,0,0,0,0,0,WFRCCenters,WFRC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37244,762164,30.0,1.9,2019.0,0,1,0,1,1,0,0,0,WFRCCenters,WFRC
37245,762167,0.0,0.4,2019.0,0,0,1,0,0,0,0,0,WFRCCenters,WFRC
37246,762168,0.0,0.4,2019.0,0,0,1,0,0,0,0,0,WFRCCenters,WFRC
37247,762169,0.0,0.4,2019.0,0,0,1,0,0,0,0,0,WFRCCenters,WFRC
37248,762170,0.0,0.4,2019.0,0,0,1,0,0,0,0,0,WFRCCenters,WFRC

In [26]:
duplicates = zpp[zpp.duplicated(subset=['parcel_id','year'])].copy()
zpp[zpp['parcel_id'] == 12457]

,parcel_id,max_dua,max_far,year,type1,type2,type3,type4,type5,type6,type7,type8,locnote,mponote
3162,12457,65.0,0.0,2019.0,1,1,0,1,1,0,0,0,CBDStaging,WFRC
3163,12457,95.0,0.0,2025.0,1,1,0,1,1,0,0,0,CBDStaging,WFRC
3164,12457,125.0,0.0,2035.0,1,1,0,1,1,0,0,0,CBDStaging,WFRC

In [13]:
b = pd.read_csv(r"E:\REMM\Base_Year_Data_2019\v1\edits\buildings_20220513.csv")
b.columns

Index(['building_id', 'building_sqft', 'building_type_id',
       'non_residential_sqft', 'note', 'parcel_id', 'residential_units',
       'stories', 'unit_price_non_residential', 'year_built',
       'res_price_per_sqft', 'job_spaces'],
      dtype='object')

In [15]:
b.building_id.value_counts()

2049      1
639597    1
623205    1
629350    1
627303    1
         ..
615814    1
617863    1
595336    1
597385    1
2047      1
Name: building_id, Length: 712527, dtype: int64

In [10]:
p = pd.read_csv(r"E:\Projects\REMM2_For_Python3_2019\data\pipeline_buildings.csv")
p.columns

Index(['building_type_id', 'non_residential_sqft', 'note', 'parcel_id',
       'residential_units', 'stories', 'unit_price_non_residential',
       'year_built', 'res_price_per_sqft', 'residential_price',
       'non_residential_price', 'job_spaces', 'building_sqft', 'DEVTYPE',
       'source'],
      dtype='object')

In [12]:
p.drop_duplicates(['parcel_id', 'year_built']).to_csv('pipeline_buildings.csv')

In [17]:
j = pd.read_csv(r"E:\REMM\Base_Year_Data_2019\v1\edits\jobs_20220513.csv")
j.columns

Index(['jobs_id', 'building_id', 'cid', 'sector_id'], dtype='object')

In [22]:
b[b.duplicated(['building_id'])]

Empty DataFrame
Columns: [building_id, building_sqft, building_type_id, non_residential_sqft, note, parcel_id, residential_units, stories, unit_price_non_residential, year_built, res_price_per_sqft, job_spaces]
Index: []