In [1]:
import pandas as pd
import os

# Update these paths!

In [2]:
# Number of model runs?
# mode = 2
# mode = 3
# mode = 5
mode = 6
# mode = 8

# store paths to se runs
path1 = r"\\server1\Volumef\SHARED\Andy\_FromJosh\New REMM Results\result_20221227\mq1"
path2 = r"\\server1\Volumef\SHARED\Andy\_FromJosh\New REMM Results\result_20221227\mq2"
path3 = r"\\server1\Volumef\SHARED\Andy\_FromJosh\New REMM Results\result_20221227\mq3"
path4 = r"\\server1\Volumef\SHARED\Andy\_FromJosh\New REMM Results\result_20221227\mq4"
path5 = r"\\server1\Volumef\SHARED\Andy\_FromJosh\New REMM Results\result_20221227\mq5"
path6 = r"\\server1\Volumef\SHARED\Andy\_FromJosh\New REMM Results\result_20221227\mq6"
# path7 = r"\\server1\Volumef\SHARED\Andy\_FromJosh\New REMM Results\result_20221211\mq1088"
# path8 = r"\\server1\Volumef\SHARED\Andy\_FromJosh\New REMM Results\result_20221010\mq872"

# output folder
data_folder = r"\\server1\Volumef\SHARED\Andy\_FromJosh\New REMM Results\result_20221227"

# Calculate and Export the Average

In [3]:
# create new output folders
output_folder = os.path.join(data_folder, '_Averaged_Results')
v900_folder = os.path.join(output_folder, 'v900',f'{mode}runs')
v832_folder = os.path.join(output_folder, 'v832',f'{mode}runs')

if not os.path.exists(output_folder):
    os.makedirs(output_folder)

if not os.path.exists(v900_folder):
    os.makedirs(v900_folder)

if not os.path.exists(v832_folder):
    os.makedirs(v832_folder)

In [4]:
# for version 900
for year in range(2019,2051):

    if mode == 2:
        run1 = pd.read_csv(os.path.join(path1, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run2 = pd.read_csv(os.path.join(path2, f"taz900_SE_{year}.csv"), index_col = ";TAZID")

        # check taz count
        if run1['TOTHH'].count() != 3546:
            print(year)
        if run2['TOTHH'].count() != 3546:
            print(year)

        runaverage = run1.copy()
        runaverage['TOTHH'] = ((run1.TOTHH + run2.TOTHH)/2.0)
        runaverage['HHPOP'] = ((run1.HHPOP + run2.HHPOP)/2.0)
        runaverage['RETL'] = ((run1.RETL + run2.RETL)/2.0)
        runaverage['FOOD'] = ((run1.FOOD + run2.FOOD)/2.0)
        runaverage['MANU'] = ((run1.MANU + run2.MANU)/2.0)
        runaverage['WSLE'] = ((run1.WSLE + run2.WSLE)/2.0)
        runaverage['OFFI'] = ((run1.OFFI + run2.OFFI)/2.0)
        runaverage['GVED'] = ((run1.GVED + run2.GVED)/2.0)
        runaverage['HLTH'] = ((run1.HLTH + run2.HLTH)/2.0)
        runaverage['OTHR'] = ((run1.OTHR + run2.OTHR)/2.0)
        runaverage['FM_AGRI'] = ((run1.FM_AGRI + run2.FM_AGRI)/2.0)
        runaverage['FM_MING'] = ((run1.FM_MING + run2.FM_MING)/2.0)
        runaverage['FM_CONS'] = ((run1.FM_CONS + run2.FM_CONS)/2.0)
        runaverage['HBJ'] = ((run1.HBJ + run2.HBJ)/2.0)

    if mode == 3:
        run1 = pd.read_csv(os.path.join(path1, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run2 = pd.read_csv(os.path.join(path2, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run3 = pd.read_csv(os.path.join(path3, f"taz900_SE_{year}.csv"), index_col = ";TAZID")


        # check taz count
        if run1['TOTHH'].count() != 3546:
            print(year)
        if run2['TOTHH'].count() != 3546:
            print(year)
        if run3['TOTHH'].count() != 3546:
            print(year)

        runaverage = run1.copy()
        runaverage['TOTHH'] = ((run1.TOTHH + run2.TOTHH + run3.TOTHH)/3.0)
        runaverage['HHPOP'] = ((run1.HHPOP + run2.HHPOP + run3.HHPOP)/3.0)
        runaverage['RETL'] = ((run1.RETL + run2.RETL + run3.RETL)/3.0)
        runaverage['FOOD'] = ((run1.FOOD + run2.FOOD + run3.FOOD)/3.0)
        runaverage['MANU'] = ((run1.MANU + run2.MANU + run3.MANU)/3.0)
        runaverage['WSLE'] = ((run1.WSLE + run2.WSLE + run3.WSLE)/3.0)
        runaverage['OFFI'] = ((run1.OFFI + run2.OFFI + run3.OFFI)/3.0)
        runaverage['GVED'] = ((run1.GVED + run2.GVED + run3.GVED)/3.0)
        runaverage['HLTH'] = ((run1.HLTH + run2.HLTH + run3.HLTH)/3.0)
        runaverage['OTHR'] = ((run1.OTHR + run2.OTHR + run3.OTHR)/3.0)
        runaverage['FM_AGRI'] = ((run1.FM_AGRI + run2.FM_AGRI + run3.FM_AGRI)/3.0)
        runaverage['FM_MING'] = ((run1.FM_MING + run2.FM_MING + run3.FM_MING)/3.0)
        runaverage['FM_CONS'] = ((run1.FM_CONS + run2.FM_CONS + run3.FM_CONS)/3.0)
        runaverage['HBJ'] = ((run1.HBJ + run2.HBJ + run3.HBJ)/3.0)

    if mode == 5:
        run1 = pd.read_csv(os.path.join(path1, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run2 = pd.read_csv(os.path.join(path2, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run3 = pd.read_csv(os.path.join(path3, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run4 = pd.read_csv(os.path.join(path4, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run5 = pd.read_csv(os.path.join(path5, f"taz900_SE_{year}.csv"), index_col = ";TAZID")


        # check taz count
        if run1['TOTHH'].count() != 3546:
            print(year)
        if run2['TOTHH'].count() != 3546:
            print(year)
        if run3['TOTHH'].count() != 3546:
            print(year)
        if run4['TOTHH'].count() != 3546:
            print(year)
        if run5['TOTHH'].count() != 3546:
            print(year)

        runaverage = run1.copy()
        runaverage['TOTHH'] = ((run1.TOTHH + run2.TOTHH + run3.TOTHH + run4.TOTHH + run5.TOTHH)/5.0)
        runaverage['HHPOP'] = ((run1.HHPOP + run2.HHPOP + run3.HHPOP + run4.HHPOP + run5.HHPOP)/5.0)
        runaverage['RETL'] = ((run1.RETL + run2.RETL + run3.RETL + run4.RETL + run5.RETL)/5.0)
        runaverage['FOOD'] = ((run1.FOOD + run2.FOOD + run3.FOOD + run4.FOOD + run5.FOOD)/5.0)
        runaverage['MANU'] = ((run1.MANU + run2.MANU + run3.MANU + run4.MANU + run5.MANU)/5.0)
        runaverage['WSLE'] = ((run1.WSLE + run2.WSLE + run3.WSLE + run4.WSLE + run5.WSLE)/5.0)
        runaverage['OFFI'] = ((run1.OFFI + run2.OFFI + run3.OFFI + run4.OFFI + run5.OFFI)/5.0)
        runaverage['GVED'] = ((run1.GVED + run2.GVED + run3.GVED + run4.GVED + run5.GVED)/5.0)
        runaverage['HLTH'] = ((run1.HLTH + run2.HLTH + run3.HLTH + run4.HLTH + run5.HLTH)/5.0)
        runaverage['OTHR'] = ((run1.OTHR + run2.OTHR + run3.OTHR + run4.OTHR + run5.OTHR)/5.0)
        runaverage['FM_AGRI'] = ((run1.FM_AGRI + run2.FM_AGRI + run3.FM_AGRI + run4.FM_AGRI + run5.FM_AGRI)/5.0)
        runaverage['FM_MING'] = ((run1.FM_MING + run2.FM_MING + run3.FM_MING + run4.FM_MING + run5.FM_MING)/5.0)
        runaverage['FM_CONS'] = ((run1.FM_CONS + run2.FM_CONS + run3.FM_CONS + run4.FM_CONS + run5.FM_CONS)/5.0)
        runaverage['HBJ'] = ((run1.HBJ + run2.HBJ + run3.HBJ + run4.HBJ + run5.HBJ)/5.0)


    if mode == 6:
        run1 = pd.read_csv(os.path.join(path1, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run2 = pd.read_csv(os.path.join(path2, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run3 = pd.read_csv(os.path.join(path3, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run4 = pd.read_csv(os.path.join(path4, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run5 = pd.read_csv(os.path.join(path5, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run6 = pd.read_csv(os.path.join(path6, f"taz900_SE_{year}.csv"), index_col = ";TAZID")


        # check taz count
        if run1['TOTHH'].count() != 3546:
            print(year)
        if run2['TOTHH'].count() != 3546:
            print(year)
        if run3['TOTHH'].count() != 3546:
            print(year)
        if run4['TOTHH'].count() != 3546:
            print(year)
        if run5['TOTHH'].count() != 3546:
            print(year)
        if run6['TOTHH'].count() != 3546:
            print(year)

        runaverage = run1.copy()
        runaverage['TOTHH'] = ((run1.TOTHH + run2.TOTHH + run3.TOTHH + run4.TOTHH + run5.TOTHH + run6.TOTHH)/6.0)
        runaverage['HHPOP'] = ((run1.HHPOP + run2.HHPOP + run3.HHPOP + run4.HHPOP + run5.HHPOP + run6.HHPOP)/6.0)
        runaverage['RETL'] = ((run1.RETL + run2.RETL + run3.RETL + run4.RETL + run5.RETL + run6.RETL)/6.0)
        runaverage['FOOD'] = ((run1.FOOD + run2.FOOD + run3.FOOD + run4.FOOD + run5.FOOD + run6.FOOD)/6.0)
        runaverage['MANU'] = ((run1.MANU + run2.MANU + run3.MANU + run4.MANU + run5.MANU + run6.MANU)/6.0)
        runaverage['WSLE'] = ((run1.WSLE + run2.WSLE + run3.WSLE + run4.WSLE + run5.WSLE + run6.WSLE)/6.0)
        runaverage['OFFI'] = ((run1.OFFI + run2.OFFI + run3.OFFI + run4.OFFI + run5.OFFI + run6.OFFI)/6.0)
        runaverage['GVED'] = ((run1.GVED + run2.GVED + run3.GVED + run4.GVED + run5.GVED + run6.GVED)/6.0)
        runaverage['HLTH'] = ((run1.HLTH + run2.HLTH + run3.HLTH + run4.HLTH + run5.HLTH + run6.HLTH)/6.0)
        runaverage['OTHR'] = ((run1.OTHR + run2.OTHR + run3.OTHR + run4.OTHR + run5.OTHR + run6.OTHR)/6.0)
        runaverage['FM_AGRI'] = ((run1.FM_AGRI + run2.FM_AGRI + run3.FM_AGRI + run4.FM_AGRI + run5.FM_AGRI + run6.FM_AGRI)/6.0)
        runaverage['FM_MING'] = ((run1.FM_MING + run2.FM_MING + run3.FM_MING + run4.FM_MING + run5.FM_MING + run6.FM_MING)/6.0)
        runaverage['FM_CONS'] = ((run1.FM_CONS + run2.FM_CONS + run3.FM_CONS + run4.FM_CONS + run5.FM_CONS + run6.FM_CONS)/6.0)
        runaverage['HBJ'] = ((run1.HBJ + run2.HBJ + run3.HBJ + run4.HBJ + run5.HBJ + run6.HBJ)/6.0)
    
    if mode == 8:
        run1 = pd.read_csv(os.path.join(path1, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run2 = pd.read_csv(os.path.join(path2, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run3 = pd.read_csv(os.path.join(path3, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run4 = pd.read_csv(os.path.join(path4, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run5 = pd.read_csv(os.path.join(path5, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run6 = pd.read_csv(os.path.join(path6, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run7 = pd.read_csv(os.path.join(path7, f"taz900_SE_{year}.csv"), index_col = ";TAZID")
        run8 = pd.read_csv(os.path.join(path8, f"taz900_SE_{year}.csv"), index_col = ";TAZID")

        # check taz count
        if run1['TOTHH'].count() != 3546:
            print(year)
        if run2['TOTHH'].count() != 3546:
            print(year)
        if run3['TOTHH'].count() != 3546:
            print(year)
        if run4['TOTHH'].count() != 3546:
            print(year)
        if run5['TOTHH'].count() != 3546:
            print(year)
        if run6['TOTHH'].count() != 3546:
            print(year)
        if run7['TOTHH'].count() != 3546:
            print(year)
        if run8['TOTHH'].count() != 3546:
            print(year)

        runaverage = run1.copy()
        runaverage['TOTHH'] = ((run1.TOTHH + run2.TOTHH + run3.TOTHH + run4.TOTHH + run5.TOTHH + run6.TOTHH + run7.TOTHH + run8.TOTHH)/8.0)
        runaverage['HHPOP'] = ((run1.HHPOP + run2.HHPOP + run3.HHPOP + run4.HHPOP + run5.HHPOP + run6.HHPOP + run7.HHPOP + run8.HHPOP)/8.0)
        runaverage['RETL'] = ((run1.RETL + run2.RETL + run3.RETL + run4.RETL + run5.RETL + run6.RETL + run7.RETL + run8.RETL)/8.0)
        runaverage['FOOD'] = ((run1.FOOD + run2.FOOD + run3.FOOD + run4.FOOD + run5.FOOD + run6.FOOD + run7.FOOD + run8.FOOD)/8.0)
        runaverage['MANU'] = ((run1.MANU + run2.MANU + run3.MANU + run4.MANU + run5.MANU + run6.MANU + run7.MANU + run8.MANU)/8.0)
        runaverage['WSLE'] = ((run1.WSLE + run2.WSLE + run3.WSLE + run4.WSLE + run5.WSLE + run6.WSLE + run7.WSLE + run8.WSLE)/8.0)
        runaverage['OFFI'] = ((run1.OFFI + run2.OFFI + run3.OFFI + run4.OFFI + run5.OFFI + run6.OFFI + run7.OFFI + run8.OFFI)/8.0)
        runaverage['GVED'] = ((run1.GVED + run2.GVED + run3.GVED + run4.GVED + run5.GVED + run6.GVED + run7.GVED + run8.GVED)/8.0)
        runaverage['HLTH'] = ((run1.HLTH + run2.HLTH + run3.HLTH + run4.HLTH + run5.HLTH + run6.HLTH + run7.HLTH + run8.HLTH)/8.0)
        runaverage['OTHR'] = ((run1.OTHR + run2.OTHR + run3.OTHR + run4.OTHR + run5.OTHR + run6.OTHR + run7.OTHR + run8.OTHR)/8.0)
        runaverage['FM_AGRI'] = ((run1.FM_AGRI + run2.FM_AGRI + run3.FM_AGRI + run4.FM_AGRI + run5.FM_AGRI + run6.FM_AGRI + run7.FM_AGRI + run8.FM_AGRI)/8.0)
        runaverage['FM_MING'] = ((run1.FM_MING + run2.FM_MING + run3.FM_MING + run4.FM_MING + run5.FM_MING + run6.FM_MING + run7.FM_MING + run8.FM_MING)/8.0)
        runaverage['FM_CONS'] = ((run1.FM_CONS + run2.FM_CONS + run3.FM_CONS + run4.FM_CONS + run5.FM_CONS + run6.FM_CONS + run7.FM_CONS + run8.FM_CONS)/8.0)
        runaverage['HBJ'] = ((run1.HBJ + run2.HBJ + run3.HBJ + run4.HBJ + run5.HBJ + run6.HBJ + run7.HBJ + run8.HBJ)/8.0)
    
    
    
    runaverage['HHSIZE'] = 0
    runaverage.loc[runaverage['TOTHH'] > 0, 'HHSIZE'] = runaverage.HHPOP[runaverage.TOTHH > 0]/runaverage.TOTHH[runaverage.TOTHH > 0]
    
    runaverage['ALLEMP'] = (runaverage['RETL']+runaverage['FOOD']+runaverage['MANU']+runaverage['WSLE']+runaverage['OFFI']+runaverage['GVED']+runaverage['HLTH']+
                            runaverage['OTHR']+runaverage['FM_AGRI']+runaverage['FM_MING']+runaverage['FM_CONS']+runaverage['HBJ'])
    runaverage['RETEMP'] = runaverage['RETL'] + runaverage['FOOD']
    runaverage['INDEMP'] = runaverage['MANU'] + runaverage['WSLE']
    runaverage['OTHEMP'] = runaverage['OFFI'] + runaverage['GVED'] + runaverage['HLTH'] + runaverage['OTHR']
    runaverage['TOTEMP'] = runaverage['RETEMP'] + runaverage['INDEMP'] + runaverage['OTHEMP']

    # export
    runaverage.to_csv(os.path.join(v900_folder, f"SE_{year}.csv" ))

In [5]:
# for version 832 model runs
for year in range(2019,2051):

    if mode == 2:
        run1 = pd.read_csv(os.path.join(path1, f"SE_{year}.csv"), index_col = ";TAZID")
        run2 = pd.read_csv(os.path.join(path2, f"SE_{year}.csv"), index_col = ";TAZID")

        # check taz count
        if run1['TOTHH'].count() != 2881:
            print(year)
        if run2['TOTHH'].count() != 2881:
            print(year)

        runaverage = run1.copy()
        runaverage['TOTHH'] = ((run1.TOTHH + run2.TOTHH)/2.0)
        runaverage['HHPOP'] = ((run1.HHPOP + run2.HHPOP)/2.0)
        runaverage['RETL'] = ((run1.RETL + run2.RETL)/2.0)
        runaverage['FOOD'] = ((run1.FOOD + run2.FOOD)/2.0)
        runaverage['MANU'] = ((run1.MANU + run2.MANU)/2.0)
        runaverage['WSLE'] = ((run1.WSLE + run2.WSLE)/2.0)
        runaverage['OFFI'] = ((run1.OFFI + run2.OFFI)/2.0)
        runaverage['GVED'] = ((run1.GVED + run2.GVED)/2.0)
        runaverage['HLTH'] = ((run1.HLTH + run2.HLTH)/2.0)
        runaverage['OTHR'] = ((run1.OTHR + run2.OTHR)/2.0)
        runaverage['FM_AGRI'] = ((run1.FM_AGRI + run2.FM_AGRI)/2.0)
        runaverage['FM_MING'] = ((run1.FM_MING + run2.FM_MING)/2.0)
        runaverage['FM_CONS'] = ((run1.FM_CONS + run2.FM_CONS)/2.0)
        runaverage['HBJ'] = ((run1.HBJ + run2.HBJ)/2.0)
     
    if mode == 3:
        run1 = pd.read_csv(os.path.join(path1, f"SE_{year}.csv"), index_col = ";TAZID")
        run2 = pd.read_csv(os.path.join(path2, f"SE_{year}.csv"), index_col = ";TAZID")
        run3 = pd.read_csv(os.path.join(path3, f"SE_{year}.csv"), index_col = ";TAZID")

        # check taz count
        if run1['TOTHH'].count() != 2881:
            print(year)
        if run2['TOTHH'].count() != 2881:
            print(year)
        if run3['TOTHH'].count() != 2881:
            print(year)

        runaverage = run1.copy()
        runaverage['TOTHH'] = ((run1.TOTHH + run2.TOTHH + run3.TOTHH)/3.0)
        runaverage['HHPOP'] = ((run1.HHPOP + run2.HHPOP + run3.HHPOP)/3.0)
        runaverage['RETL'] = ((run1.RETL + run2.RETL + run3.RETL)/3.0)
        runaverage['FOOD'] = ((run1.FOOD + run2.FOOD + run3.FOOD)/3.0)
        runaverage['MANU'] = ((run1.MANU + run2.MANU + run3.MANU)/3.0)
        runaverage['WSLE'] = ((run1.WSLE + run2.WSLE + run3.WSLE)/3.0)
        runaverage['OFFI'] = ((run1.OFFI + run2.OFFI + run3.OFFI)/3.0)
        runaverage['GVED'] = ((run1.GVED + run2.GVED + run3.GVED)/3.0)
        runaverage['HLTH'] = ((run1.HLTH + run2.HLTH + run3.HLTH)/3.0)
        runaverage['OTHR'] = ((run1.OTHR + run2.OTHR + run3.OTHR)/3.0)
        runaverage['FM_AGRI'] = ((run1.FM_AGRI + run2.FM_AGRI + run3.FM_AGRI)/3.0)
        runaverage['FM_MING'] = ((run1.FM_MING + run2.FM_MING + run3.FM_MING)/3.0)
        runaverage['FM_CONS'] = ((run1.FM_CONS + run2.FM_CONS + run3.FM_CONS)/3.0)
        runaverage['HBJ'] = ((run1.HBJ + run2.HBJ + run3.HBJ)/3.0)

    if mode == 5:
        run1 = pd.read_csv(os.path.join(path1, f"SE_{year}.csv"), index_col = ";TAZID")
        run2 = pd.read_csv(os.path.join(path2, f"SE_{year}.csv"), index_col = ";TAZID")
        run3 = pd.read_csv(os.path.join(path3, f"SE_{year}.csv"), index_col = ";TAZID")
        run4 = pd.read_csv(os.path.join(path4, f"SE_{year}.csv"), index_col = ";TAZID")
        run5 = pd.read_csv(os.path.join(path5, f"SE_{year}.csv"), index_col = ";TAZID")

        # check taz count
        if run1['TOTHH'].count() != 2881:
            print(year)
        if run2['TOTHH'].count() != 2881:
            print(year)
        if run3['TOTHH'].count() != 2881:
            print(year)
        if run4['TOTHH'].count() != 2881:
            print(year)
        if run5['TOTHH'].count() != 2881:
            print(year)

        runaverage = run1.copy()
        runaverage['TOTHH'] = ((run1.TOTHH + run2.TOTHH + run3.TOTHH + run4.TOTHH + run5.TOTHH)/5.0)
        runaverage['HHPOP'] = ((run1.HHPOP + run2.HHPOP + run3.HHPOP + run4.HHPOP + run5.HHPOP)/5.0)
        runaverage['RETL'] = ((run1.RETL + run2.RETL + run3.RETL + run4.RETL + run5.RETL)/5.0)
        runaverage['FOOD'] = ((run1.FOOD + run2.FOOD + run3.FOOD + run4.FOOD + run5.FOOD)/5.0)
        runaverage['MANU'] = ((run1.MANU + run2.MANU + run3.MANU + run4.MANU + run5.MANU)/5.0)
        runaverage['WSLE'] = ((run1.WSLE + run2.WSLE + run3.WSLE + run4.WSLE + run5.WSLE)/5.0)
        runaverage['OFFI'] = ((run1.OFFI + run2.OFFI + run3.OFFI + run4.OFFI + run5.OFFI)/5.0)
        runaverage['GVED'] = ((run1.GVED + run2.GVED + run3.GVED + run4.GVED + run5.GVED)/5.0)
        runaverage['HLTH'] = ((run1.HLTH + run2.HLTH + run3.HLTH + run4.HLTH + run5.HLTH)/5.0)
        runaverage['OTHR'] = ((run1.OTHR + run2.OTHR + run3.OTHR + run4.OTHR + run5.OTHR)/5.0)
        runaverage['FM_AGRI'] = ((run1.FM_AGRI + run2.FM_AGRI + run3.FM_AGRI + run4.FM_AGRI + run5.FM_AGRI)/5.0)
        runaverage['FM_MING'] = ((run1.FM_MING + run2.FM_MING + run3.FM_MING + run4.FM_MING + run5.FM_MING)/5.0)
        runaverage['FM_CONS'] = ((run1.FM_CONS + run2.FM_CONS + run3.FM_CONS + run4.FM_CONS + run5.FM_CONS)/5.0)
        runaverage['HBJ'] = ((run1.HBJ + run2.HBJ + run3.HBJ + run4.HBJ + run5.HBJ)/5.0)

    if mode == 6:
        run1 = pd.read_csv(os.path.join(path1, f"SE_{year}.csv"), index_col = ";TAZID")
        run2 = pd.read_csv(os.path.join(path2, f"SE_{year}.csv"), index_col = ";TAZID")
        run3 = pd.read_csv(os.path.join(path3, f"SE_{year}.csv"), index_col = ";TAZID")
        run4 = pd.read_csv(os.path.join(path4, f"SE_{year}.csv"), index_col = ";TAZID")
        run5 = pd.read_csv(os.path.join(path5, f"SE_{year}.csv"), index_col = ";TAZID")
        run6 = pd.read_csv(os.path.join(path6, f"SE_{year}.csv"), index_col = ";TAZID")


        # check taz count
        if run1['TOTHH'].count() != 2881:
            print(year)
        if run2['TOTHH'].count() != 2881:
            print(year)
        if run3['TOTHH'].count() != 2881:
            print(year)
        if run4['TOTHH'].count() != 2881:
            print(year)
        if run5['TOTHH'].count() != 2881:
            print(year)
        if run6['TOTHH'].count() != 2881:
            print(year)

        runaverage = run1.copy()
        runaverage['TOTHH'] = ((run1.TOTHH + run2.TOTHH + run3.TOTHH + run4.TOTHH + run5.TOTHH + run6.TOTHH)/6.0)
        runaverage['HHPOP'] = ((run1.HHPOP + run2.HHPOP + run3.HHPOP + run4.HHPOP + run5.HHPOP + run6.HHPOP)/6.0)
        runaverage['RETL'] = ((run1.RETL + run2.RETL + run3.RETL + run4.RETL + run5.RETL + run6.RETL)/6.0)
        runaverage['FOOD'] = ((run1.FOOD + run2.FOOD + run3.FOOD + run4.FOOD + run5.FOOD + run6.FOOD)/6.0)
        runaverage['MANU'] = ((run1.MANU + run2.MANU + run3.MANU + run4.MANU + run5.MANU + run6.MANU)/6.0)
        runaverage['WSLE'] = ((run1.WSLE + run2.WSLE + run3.WSLE + run4.WSLE + run5.WSLE + run6.WSLE)/6.0)
        runaverage['OFFI'] = ((run1.OFFI + run2.OFFI + run3.OFFI + run4.OFFI + run5.OFFI + run6.OFFI)/6.0)
        runaverage['GVED'] = ((run1.GVED + run2.GVED + run3.GVED + run4.GVED + run5.GVED + run6.GVED)/6.0)
        runaverage['HLTH'] = ((run1.HLTH + run2.HLTH + run3.HLTH + run4.HLTH + run5.HLTH + run6.HLTH)/6.0)
        runaverage['OTHR'] = ((run1.OTHR + run2.OTHR + run3.OTHR + run4.OTHR + run5.OTHR + run6.OTHR)/6.0)
        runaverage['FM_AGRI'] = ((run1.FM_AGRI + run2.FM_AGRI + run3.FM_AGRI + run4.FM_AGRI + run5.FM_AGRI + run6.FM_AGRI)/6.0)
        runaverage['FM_MING'] = ((run1.FM_MING + run2.FM_MING + run3.FM_MING + run4.FM_MING + run5.FM_MING + run6.FM_MING)/6.0)
        runaverage['FM_CONS'] = ((run1.FM_CONS + run2.FM_CONS + run3.FM_CONS + run4.FM_CONS + run5.FM_CONS + run6.FM_CONS)/6.0)
        runaverage['HBJ'] = ((run1.HBJ + run2.HBJ + run3.HBJ + run4.HBJ + run5.HBJ + run6.HBJ)/6.0)
    
    if mode == 8:
        run1 = pd.read_csv(os.path.join(path1, f"SE_{year}.csv"), index_col = ";TAZID")
        run2 = pd.read_csv(os.path.join(path2, f"SE_{year}.csv"), index_col = ";TAZID")
        run3 = pd.read_csv(os.path.join(path3, f"SE_{year}.csv"), index_col = ";TAZID")
        run4 = pd.read_csv(os.path.join(path4, f"SE_{year}.csv"), index_col = ";TAZID")
        run5 = pd.read_csv(os.path.join(path5, f"SE_{year}.csv"), index_col = ";TAZID")
        run6 = pd.read_csv(os.path.join(path6, f"SE_{year}.csv"), index_col = ";TAZID")
        run7 = pd.read_csv(os.path.join(path7, f"SE_{year}.csv"), index_col = ";TAZID")
        run8 = pd.read_csv(os.path.join(path8, f"SE_{year}.csv"), index_col = ";TAZID")


        # check taz count
        if run1['TOTHH'].count() != 2881:
            print(year)
        if run2['TOTHH'].count() != 2881:
            print(year)
        if run3['TOTHH'].count() != 2881:
            print(year)
        if run4['TOTHH'].count() != 2881:
            print(year)
        if run5['TOTHH'].count() != 2881:
            print(year)
        if run6['TOTHH'].count() != 2881:
            print(year)
        if run7['TOTHH'].count() != 2881:
            print(year)
        if run8['TOTHH'].count() != 2881:
            print(year)

        runaverage = run1.copy()
        runaverage['TOTHH'] = ((run1.TOTHH + run2.TOTHH + run3.TOTHH + run4.TOTHH + run5.TOTHH + run6.TOTHH + run7.TOTHH + run8.TOTHH)/8.0)
        runaverage['HHPOP'] = ((run1.HHPOP + run2.HHPOP + run3.HHPOP + run4.HHPOP + run5.HHPOP + run6.HHPOP + run7.HHPOP + run8.HHPOP)/8.0)
        runaverage['RETL'] = ((run1.RETL + run2.RETL + run3.RETL + run4.RETL + run5.RETL + run6.RETL + run7.RETL + run8.RETL)/8.0)
        runaverage['FOOD'] = ((run1.FOOD + run2.FOOD + run3.FOOD + run4.FOOD + run5.FOOD + run6.FOOD + run7.FOOD + run8.FOOD)/8.0)
        runaverage['MANU'] = ((run1.MANU + run2.MANU + run3.MANU + run4.MANU + run5.MANU + run6.MANU + run7.MANU + run8.MANU)/8.0)
        runaverage['WSLE'] = ((run1.WSLE + run2.WSLE + run3.WSLE + run4.WSLE + run5.WSLE + run6.WSLE + run7.WSLE + run8.WSLE)/8.0)
        runaverage['OFFI'] = ((run1.OFFI + run2.OFFI + run3.OFFI + run4.OFFI + run5.OFFI + run6.OFFI + run7.OFFI + run8.OFFI)/8.0)
        runaverage['GVED'] = ((run1.GVED + run2.GVED + run3.GVED + run4.GVED + run5.GVED + run6.GVED + run7.GVED + run8.GVED)/8.0)
        runaverage['HLTH'] = ((run1.HLTH + run2.HLTH + run3.HLTH + run4.HLTH + run5.HLTH + run6.HLTH + run7.HLTH + run8.HLTH)/8.0)
        runaverage['OTHR'] = ((run1.OTHR + run2.OTHR + run3.OTHR + run4.OTHR + run5.OTHR + run6.OTHR + run7.OTHR + run8.OTHR)/8.0)
        runaverage['FM_AGRI'] = ((run1.FM_AGRI + run2.FM_AGRI + run3.FM_AGRI + run4.FM_AGRI + run5.FM_AGRI + run6.FM_AGRI + run7.FM_AGRI + run8.FM_AGRI)/8.0)
        runaverage['FM_MING'] = ((run1.FM_MING + run2.FM_MING + run3.FM_MING + run4.FM_MING + run5.FM_MING + run6.FM_MING + run7.FM_MING + run8.FM_MING)/8.0)
        runaverage['FM_CONS'] = ((run1.FM_CONS + run2.FM_CONS + run3.FM_CONS + run4.FM_CONS + run5.FM_CONS + run6.FM_CONS + run7.FM_CONS + run8.FM_CONS)/8.0)
        runaverage['HBJ'] = ((run1.HBJ + run2.HBJ + run3.HBJ + run4.HBJ + run5.HBJ + run6.HBJ + run7.HBJ + run8.HBJ)/8.0)


    runaverage['HHSIZE'] = 0
    runaverage.loc[runaverage['TOTHH'] > 0, 'HHSIZE'] = runaverage.HHPOP[runaverage.TOTHH > 0]/runaverage.TOTHH[runaverage.TOTHH > 0]
    runaverage['ALLEMP'] = (runaverage['RETL']+runaverage['FOOD']+runaverage['MANU']+runaverage['WSLE']+runaverage['OFFI']+runaverage['GVED']+runaverage['HLTH']+
                            runaverage['OTHR']+runaverage['FM_AGRI']+runaverage['FM_MING']+runaverage['FM_CONS']+runaverage['HBJ'])
    runaverage['RETEMP'] = runaverage['RETL'] + runaverage['FOOD']
    runaverage['INDEMP'] = runaverage['MANU'] + runaverage['WSLE']
    runaverage['OTHEMP'] = runaverage['OFFI'] + runaverage['GVED'] + runaverage['HLTH'] + runaverage['OTHR']
    runaverage['TOTEMP'] = runaverage['RETEMP'] + runaverage['INDEMP'] + runaverage['OTHEMP']

    # export
    runaverage.to_csv(os.path.join(v832_folder, f"SE_{year}.csv" ))

# Compare the results with the Control Totals

In [11]:
employment_controls = pd.read_csv(r".\inputs\employment_controls.csv")
nonremm_taz = pd.read_csv(r".\inputs\WF NonREMM TAZ Forecast - 2022-12-20.csv")
year = 2019
se_832 = pd.read_csv(os.path.join(v832_folder, f'SE_{year}.csv'))
se_900 = pd.read_csv(os.path.join(v900_folder, f'SE_{year}.csv'))

In [12]:
ec_year = employment_controls[(employment_controls['year']== year)].copy()
employment_control_by_county_832 = ec_year.pivot(index='cid', columns='sector_id', values='number_of_jobs').reset_index()

# rename columns
lu = {'cid':'CO_FIPS', 1:'FOOD_C', 2:'FM_CONS_C', 3:'GVED_C', 4:'HLTH_C', 5:'MANU_C', 6:'OFFI_C', 7:'OTHR_C', 8:'FM_MING_C', 9:'RETL_C', 10:'WSLE_C', 11:'FM_AGRI_C', 12:'HBJ_C'}
employment_control_by_county_832.rename(lu, axis=1, inplace=True)

# SE 832: aggregate job counts by county
se_832_year = se_832[['CO_FIPS', 'RETL','FOOD','MANU',	'WSLE',	'OFFI',	'GVED',	'HLTH',	'OTHR',	'FM_AGRI',	'FM_MING',	'FM_CONS',	'HBJ']].copy()
se_832_year = se_832_year[se_832_year['CO_FIPS'].isin([0,3]) == False]
se_832_year_county_sum = se_832_year.groupby('CO_FIPS')[['RETL','FOOD','MANU','WSLE','OFFI','GVED',	'HLTH',	'OTHR',	'FM_AGRI',	'FM_MING',	'FM_CONS',	'HBJ']].sum().reset_index()

# merge and compute percentage difference
merge_832 = employment_control_by_county_832.merge(se_832_year_county_sum, on='CO_FIPS',how='left')
merge_832['RETL_DIF%'] = (merge_832['RETL'] -merge_832['RETL_C'])/merge_832['RETL_C']
merge_832['FOOD_DIF%'] = (merge_832['FOOD'] -merge_832['FOOD_C'])/merge_832['FOOD_C']
merge_832['MANU_DIF%'] = (merge_832['MANU'] -merge_832['MANU_C'])/merge_832['MANU_C']
merge_832['WSLE_DIF%'] = (merge_832['WSLE'] -merge_832['WSLE_C'])/merge_832['WSLE_C']
merge_832['OFFI_DIF%'] = (merge_832['OFFI'] -merge_832['OFFI_C'])/merge_832['OFFI_C']
merge_832['GVED_DIF%'] = (merge_832['GVED'] -merge_832['GVED_C'])/merge_832['GVED_C']
merge_832['HLTH_DIF%'] = (merge_832['HLTH'] -merge_832['HLTH_C'])/merge_832['HLTH_C']
merge_832['OTHR_DIF%'] = (merge_832['OTHR'] -merge_832['OTHR_C'])/merge_832['OTHR_C']
merge_832['AGRI_DIF%'] = (merge_832['FM_AGRI'] -merge_832['FM_AGRI_C'])/merge_832['FM_AGRI_C']
merge_832['MING_DIF%'] = (merge_832['FM_MING'] -merge_832['FM_MING_C'])/merge_832['FM_MING_C']
merge_832['CONS_DIF%'] = (merge_832['FM_CONS'] -merge_832['FM_CONS_C'])/merge_832['FM_CONS_C']
merge_832['HBJ_DIF%'] = (merge_832['HBJ'] -merge_832['HBJ_C'])/merge_832['HBJ_C']

# display table
merge_832.style.format({'RETL_DIF%': "{:.1%}",'FOOD_DIF%': "{:.1%}",'MANU_DIF%': "{:.1%}",'WSLE_DIF%': "{:.1%}",
                        'OFFI_DIF%': "{:.1%}",'GVED_DIF%': "{:.1%}",'HLTH_DIF%': "{:.1%}",'OTHR_DIF%': "{:.1%}",
                        'AGRI_DIF%': "{:.1%}",'MING_DIF%': "{:.1%}", 'CONS_DIF%': "{:.1%}",'HBJ_DIF%': "{:.1%}"})

In [13]:
# add nonremm taz to control total
nrt_year = nonremm_taz[nonremm_taz['YEAR']==year][['CO_FIPS', 'RETL','FOOD','MANU',	'WSLE',	'OFFI',	'GVED',	'HLTH',	'OTHR',	'AGRI',	'MING',	'CONS',	'HBJ']].copy()
nrt_year_county_sum = nrt_year.groupby('CO_FIPS')[['RETL','FOOD','MANU','WSLE',	'OFFI',	'GVED',	'HLTH',	'OTHR',	'AGRI',	'MING',	'CONS',	'HBJ']].sum().reset_index()
ec_nrt = employment_control_by_county_832.merge(nrt_year_county_sum, on='CO_FIPS', how='left')
ec_nrt['RETL_C'] = ec_nrt['RETL'] + ec_nrt['RETL_C']
ec_nrt['FOOD_C'] = ec_nrt['FOOD'] + ec_nrt['FOOD_C']
ec_nrt['MANU_C'] = ec_nrt['MANU'] + ec_nrt['MANU_C']
ec_nrt['WSLE_C'] = ec_nrt['WSLE'] + ec_nrt['WSLE_C']
ec_nrt['OFFI_C'] = ec_nrt['OFFI'] + ec_nrt['OFFI_C']
ec_nrt['GVED_C'] = ec_nrt['GVED'] + ec_nrt['GVED_C']
ec_nrt['HLTH_C'] = ec_nrt['HLTH'] + ec_nrt['HLTH_C']
ec_nrt['OTHR_C'] = ec_nrt['OTHR'] + ec_nrt['OTHR_C']
ec_nrt['FM_AGRI_C'] = ec_nrt['AGRI'] + ec_nrt['FM_AGRI_C']
# ec_nrt['FM_MING_C'] = ec_nrt['FM_MING_C']
ec_nrt['FM_CONS_C'] = ec_nrt['CONS'] + ec_nrt['FM_CONS_C']
ec_nrt['HBJ_C'] = ec_nrt['HBJ'] + ec_nrt['HBJ_C']
employment_control_by_county_900 = ec_nrt[['CO_FIPS', 'RETL_C','FOOD_C','MANU_C','WSLE_C','OFFI_C',	'GVED_C','HLTH_C',	'OTHR_C','FM_AGRI_C','FM_MING_C', 'FM_CONS_C','HBJ_C']].copy()

# SE 900: aggregate job counts by county
se_900_year = se_900[['CO_FIPS', 'RETL','FOOD','MANU',	'WSLE',	'OFFI',	'GVED',	'HLTH',	'OTHR',	'FM_AGRI',	'FM_MING',	'FM_CONS',	'HBJ']].copy()
se_900_year_county_sum = se_900_year.groupby('CO_FIPS')[['RETL','FOOD','MANU','WSLE',	'OFFI',	'GVED',	'HLTH',	'OTHR',	'FM_AGRI',	'FM_MING',	'FM_CONS',	'HBJ']].sum().reset_index().sort_values('CO_FIPS')


# merge and compute percentage difference
merge_900 = employment_control_by_county_900.merge(se_900_year_county_sum, on='CO_FIPS',how='left')
merge_900['RETL_DIF%'] = (merge_900['RETL'] -merge_900['RETL_C'])/merge_900['RETL_C']
merge_900['FOOD_DIF%'] = (merge_900['FOOD'] -merge_900['FOOD_C'])/merge_900['FOOD_C']
merge_900['MANU_DIF%'] = (merge_900['MANU'] -merge_900['MANU_C'])/merge_900['MANU_C']
merge_900['WSLE_DIF%'] = (merge_900['WSLE'] -merge_900['WSLE_C'])/merge_900['WSLE_C']
merge_900['OFFI_DIF%'] = (merge_900['OFFI'] -merge_900['OFFI_C'])/merge_900['OFFI_C']
merge_900['GVED_DIF%'] = (merge_900['GVED'] -merge_900['GVED_C'])/merge_900['GVED_C']
merge_900['HLTH_DIF%'] = (merge_900['HLTH'] -merge_900['HLTH_C'])/merge_900['HLTH_C']
merge_900['OTHR_DIF%'] = (merge_900['OTHR'] -merge_900['OTHR_C'])/merge_900['OTHR_C']
merge_900['AGRI_DIF%'] = (merge_900['FM_AGRI'] -merge_900['FM_AGRI_C'])/merge_900['FM_AGRI_C']
merge_900['MING_DIF%'] = (merge_900['FM_MING'] -merge_900['FM_MING_C'])/merge_900['FM_MING_C']
merge_900['CONS_DIF%'] = (merge_900['FM_CONS'] -merge_900['FM_CONS_C'])/merge_900['FM_CONS_C']
merge_900['HBJ_DIF%'] = (merge_900['HBJ'] -merge_900['HBJ_C'])/merge_900['HBJ_C']

# display table
merge_900.style.format({'RETL_DIF%': "{:.1%}",'FOOD_DIF%': "{:.1%}",'MANU_DIF%': "{:.1%}",'WSLE_DIF%': "{:.1%}",
                        'OFFI_DIF%': "{:.1%}",'GVED_DIF%': "{:.1%}",'HLTH_DIF%': "{:.1%}",'OTHR_DIF%': "{:.1%}",
                        'AGRI_DIF%': "{:.1%}",'MING_DIF%': "{:.1%}", 'CONS_DIF%': "{:.1%}",'HBJ_DIF%': "{:.1%}"})